#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use File::Spec;
use lib File::Spec->catdir($FindBin::Bin, 'lib');

use OreOre::ReadTwit;

use Getopt::Long;

my $config = File::Spec->catfile($FindBin::Bin, 'config.yaml');
GetOptions('--config=s', \$config, '--version' => \my $version);
Getopt::Long::Configure("bundling"); # allows -c -v

if ($version) {
    print "ReadTwittoru version $OreOre::Readtwit::VERSION\n";
    exit;
}

OreOre::Readtwit->bootstrap(config => $config);

